const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const formsSource = fs.readFileSync(path.join(root, 'admin-forms.js'), 'utf8');
const formRoot = { innerHTML: '' };
vm.runInNewContext(formsSource, { window: { PAGE_NAME: 'overview' }, document: { querySelector: () => formRoot } });
const forms = formRoot.innerHTML;
const areaRoot = { innerHTML: '' };
vm.runInNewContext(formsSource, { window: { PAGE_NAME: 'areas' }, document: { querySelector: () => areaRoot } });
assert.match(areaRoot.innerHTML, /id="deliveryAreaForm"[\s\S]*选择区域/, '配送区域页必须保留原有选择器表单');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const mediaGuide = fs.readFileSync(path.join(root, 'admin-media-guide.js'), 'utf8');
const api = fs.readFileSync(path.join(root, 'api-client.js'), 'utf8');
const config = fs.readFileSync(path.join(root, 'config.js'), 'utf8');

assert.match(config, /cloud1-d8gp843lt5454ada7/, '后台必须指向当前 CloudBase 环境');
assert.match(html, /admin-forms\.js/, '后台页面必须加载共享表单模块');
assert.match(forms, /name="uploadFile"\s+type="file"/, '素材表单必须提供人工选择文件入口');
assert.match(forms, /上传并登记素材/, '素材表单必须明确人工上传动作');
assert.match(api, /async function uploadMediaFile/, '后台 API 客户端必须提供受控上传调用');
assert.match(api, /admin\.media\.upload/, '后台上传必须走管理员云函数动作');
assert.match(mediaGuide, /api\.uploadMediaFile\(file, type/, '提交素材时必须先通过后台上传文件');
assert.match(mediaGuide, /admin\.media\.createVersion|admin\.media\.upsert/, '上传成功后必须登记媒体记录');
assert.doesNotMatch(forms, /CloudBase 文件 ID|name="fileId"|name="mimeType"|name="sizeBytes"/, '素材表单不可要求运营人员填写云存储内部字段');
assert.match(forms, /id="productMediaForm"/, '后台必须提供商品媒体人工关联表单');
assert.match(forms, /保存商品媒体关联/, '商品媒体表单必须明确关联保存动作');
assert.match(app, /admin\.productMedia\.upsert/, '商品媒体关联必须走后台云函数动作');
assert.match(app, /admin\.productMedia\.list/, '后台必须加载商品媒体关联列表');
const confirmAt = mediaGuide.indexOf('global.confirm');
const mediaWriteAt = mediaGuide.indexOf("call(replacing ? 'admin.media.createVersion' : 'admin.media.upsert'");
assert.ok(confirmAt > -1 && confirmAt < mediaWriteAt, '素材登记（含新建版本）必须在发起写请求前确认，未确认不得提交');
assert.match(mediaGuide, /素材名称：\$\{payload/, '确认文案必须显示素材名称');
assert.match(mediaGuide, /类型：\$\{typeLabel\}/, '确认文案必须显示素材类型');
assert.match(mediaGuide, /新版本会影响既有引用/, '新建版本的确认文案必须说明会影响既有引用');
assert.match(mediaGuide, /已取消登记[\s\S]{0,120}?return; \}\s*await call\(replacing \?/, '取消确认时必须直接返回，不发起登记写请求');
console.log('admin media upload UI contract: passed');
