const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const nodes = Object.fromEntries(['taskMetrics', 'overviewDate', 'metrics', 'overviewOrders', 'overviewQueue'].map((key) => [key, { innerHTML: '', textContent: '' }]));
const window = {};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../admin-overview.js'), 'utf8'), { window, document: { getElementById: (key) => nodes[key] } });
const state = { orders: [], products: [], skus: [], refunds: [], businessApplications: [], loadStates: {} };
const render = window.MengshixianAdminOverview.render;
render(state);
assert.match(nodes.taskMetrics.innerHTML, /正在读取/);
assert.doesNotMatch(nodes.overviewQueue.innerHTML, /没有待处理事项/);
state.loadStates = { orders: 'failed', products: 'ready', skus: 'ready', refunds: 'ready', businessApplications: 'ready' };
render(state);
assert.match(nodes.overviewOrders.innerHTML, /暂不可用/);
assert.doesNotMatch(nodes.overviewOrders.innerHTML, /没有订单/);
assert.doesNotMatch(nodes.overviewQueue.innerHTML, /没有待处理事项/);
state.loadStates.orders = 'ready';
render(state);
assert.match(nodes.overviewOrders.innerHTML, /当前没有订单记录/);
assert.match(nodes.overviewQueue.innerHTML, /没有待处理事项/);
state.orders.push({ status: 'picking', orderNo: 'TEST-1' });
render(state);
assert.match(nodes.overviewQueue.innerHTML, /待拣货订单/);
console.log('Overview distinguishes loading, unavailable, empty and actionable states: passed');
