const assert = require('node:assert/strict');
const { createCatalogFixture } = require('./support/catalog-flow-fixture.cjs');
async function main() {
  const fixture = await createCatalogFixture();
  const input = {username:'local-operator',displayName:'本地运营',phone:'13800138000',role:'operator',password:'local-operator-password',status:'active'};
  const staff = await fixture.call('admin.staff.create', input);
  assert.ok(staff.id);
  assert.equal(staff.role, 'operator');
  assert.equal(staff.phoneMasked, '138****8000');
  assert.equal(staff.phoneVerificationStatus, 'unverified');
  assert.equal(staff.phoneVerifiedAt, null);
  assert.equal(staff.permissions.includes('receipts.write'), true);
  assert.equal(staff.permissions.includes('admin.write'), false);
  assert.equal(staff.permissions.includes('*'), false);
  assert.equal(staff.permissions.includes('refunds.write'), false);
  assert.ok(!JSON.stringify(staff).includes(input.password));
  assert.ok(!JSON.stringify(staff).includes(input.phone));
  const login = await fixture.call('admin.login', {username:input.username,password:input.password});
  const me = await fixture.call('admin.me', {adminToken:login.token});
  assert.equal(me.admin.id, staff.id);
  assert.equal(me.admin.phoneVerificationStatus, 'unverified');
  await fixture.call('admin.products.list', {adminToken:login.token});
  await assert.rejects(fixture.call('admin.staff.create', {...input,username:'forbidden',adminToken:login.token}), e => e.code === 'ADMIN_FORBIDDEN');
  await assert.rejects(fixture.call('admin.staff.create', {...input,username:'fake-verified',phoneVerificationStatus:'verified'}), e => e.code === 'STAFF_VERIFICATION_FORBIDDEN');
  await assert.rejects(fixture.call('admin.staff.create', {...input,username:'fake-permissions',permissions:['*']}), e => e.code === 'STAFF_PERMISSIONS_FORBIDDEN');
  await assert.rejects(fixture.call('admin.staff.create', input), e => e.code === 'STAFF_USERNAME_EXISTS');
  const roles = (await fixture.call('admin.roles.list', {})).rows;
  const legacyUpdate = {id:staff.id,username:input.username,displayName:'不应被修改',roleIds:[roles[0]._id],status:'disabled'};
  await assert.rejects(fixture.call('admin.adminUsers.upsert', legacyUpdate), e => e.code === 'STAFF_USE_ACCOUNT_MANAGER');
  assert.equal((await fixture.call('admin.me', {adminToken:login.token})).admin.status, 'active');
  await assert.rejects(fixture.call('admin.roles.upsert', {code:'custom-role',name:'其他角色',permissions:['catalog.read']}), e => e.code === 'STAFF_USE_ACCOUNT_MANAGER');
  await assert.rejects(fixture.call('admin.adminUsers.upsert', {username:'legacy-new-user',displayName:'旧入口新增',password:'local-legacy-password',roleIds:[roles[0]._id]}), e => e.code === 'STAFF_USE_ACCOUNT_MANAGER');
  const logs = (await fixture.call('admin.audit.list', {pageSize:100})).rows.filter(row => row.action === 'staff.create');
  assert.equal(logs.length, 1);
  assert.equal(logs[0].targetId, staff.id);
  assert.ok(logs[0].actorId && logs[0].createdAt);
  assert.ok(!JSON.stringify(logs).includes(input.phone));
  await fixture.call('admin.logout', {adminToken:login.token});
  await assert.rejects(fixture.call('admin.me', {adminToken:login.token}), e => e.code === 'ADMIN_SESSION_EXPIRED');
  console.log('Staff actual API: operator creation, unverified masked phone, limited permissions, audit and revoked session');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
