(function mountAdminForms(global, document) {
  // One source for edit forms shared by the independent admin pages.
  const forms = [
    "<form class=\"card form-card\" id=\"categoryForm\"><h3>新增或修改分类</h3><input type=\"hidden\" name=\"id\"><label>分类名称<input name=\"name\" required maxlength=\"30\"></label><label>分类图片（从素材库选择）<input name=\"imageMediaId\" placeholder=\"可稍后补充\"></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"enabled\">启用</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存分类</button></form>",
    "<form class=\"card form-card\" id=\"productForm\"><h3>商品信息</h3><input type=\"hidden\" name=\"id\"><label>商品名称<input name=\"name\" required maxlength=\"100\"></label><label>分类<input name=\"categoryId\" list=\"categoryOptions\" required><datalist id=\"categoryOptions\"></datalist></label><label>品牌<input name=\"brand\" maxlength=\"60\"></label><label>产地<input name=\"origin\" maxlength=\"80\"></label><label>储存温度<input name=\"frozenTemperature\" value=\"-18℃\" maxlength=\"30\"></label><label>商品主图素材<input name=\"coverMediaId\"></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><button class=\"primary\">保存商品</button></form>",
    "<form class=\"card form-card\" id=\"skuForm\"><h3>SKU 规格</h3><input type=\"hidden\" name=\"id\"><label>关联商品 ID<input name=\"productId\" required></label><label>规格名称<input name=\"specName\" required maxlength=\"100\"></label><label>包装单位<input name=\"packageUnit\" maxlength=\"100\"></label><label>净含量<input name=\"netWeight\" maxlength=\"40\"></label><label>重量单位<input name=\"weightUnit\" maxlength=\"20\"></label><label>每箱数量<input name=\"piecesPerCase\" type=\"number\" value=\"0\"></label><label>条码<input name=\"barcode\" maxlength=\"60\"></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"on_sale\">上架</option><option value=\"off_sale\">下架</option></select></label><button class=\"primary\">保存 SKU</button></form>",
    "<form class=\"card form-card\" id=\"productMediaForm\"><h3>商品详情媒体关联</h3><p class=\"muted\">先在素材库上传并登记，再把素材 ID 关联到具体商品。视频使用\"详情\"角色，保存后才会出现在小程序商品详情页。</p><input type=\"hidden\" name=\"id\"><label>商品 ID<input name=\"productId\" required list=\"productMediaProductOptions\"></label><datalist id=\"productMediaProductOptions\"></datalist><label>SKU ID（可选）<input name=\"skuId\" list=\"skuOptions\"></label><label>素材 ID<input name=\"mediaAssetId\" required list=\"mediaAssetOptions\"></label><datalist id=\"mediaAssetOptions\"></datalist><label>媒体类型<select name=\"mediaType\"><option value=\"image\">图片</option><option value=\"video\">视频</option></select></label><label>角色<select name=\"role\"><option value=\"cover\">封面</option><option value=\"detail\" selected>详情</option><option value=\"video_cover\">视频封面</option><option value=\"instruction\">说明</option></select></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><label class=\"checkbox\"><input name=\"enabled\" type=\"checkbox\" checked>启用</label><button class=\"primary\">保存商品媒体关联</button></form>",
    "<form class=\"card form-card\" id=\"priceForm\"><h3>价格规则</h3><input type=\"hidden\" name=\"id\"><label>商品规格<input name=\"skuId\" required list=\"skuOptions\"></label><datalist id=\"skuOptions\"></datalist><label>适用范围<select name=\"scopeType\"><option value=\"public\">所有登录用户</option><option value=\"customer_type\">客户类型</option><option value=\"level\">会员等级</option><option value=\"organization\">企业组织</option><option value=\"user\">指定用户</option></select></label><label>适用对象<input name=\"scopeId\" placeholder=\"公开价可留空\"></label><label>适用端<select name=\"channel\"><option value=\"all\">全部端</option><option value=\"miniapp\">小程序</option><option value=\"web\">网页端</option></select></label><label>价格（元）<input name=\"amountCent\" type=\"number\" min=\"0\" required placeholder=\"例如：25.00\"></label><label>优先级<input name=\"priority\" type=\"number\" value=\"0\"></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"active\">生效</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存价格规则</button></form>",
    "<form class=\"card form-card\" id=\"warehouseForm\"><h3>仓库</h3><input type=\"hidden\" name=\"id\"><label>仓库编码<input name=\"code\" required maxlength=\"40\"></label><label>仓库名称<input name=\"name\" required maxlength=\"80\"></label><label>地址<input name=\"address\" maxlength=\"200\"></label><label>状态<select name=\"status\"><option value=\"active\">启用</option><option value=\"disabled\">停用</option></select></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><button class=\"primary\">保存仓库</button></form>",
    "<form class=\"card form-card\" id=\"deliveryAreaForm\"><h3>配送区域</h3><input type=\"hidden\" name=\"id\"><label>区域名称<input name=\"name\" required maxlength=\"80\"></label><label>区域编码<textarea name=\"regionCodes\" required placeholder=\"每行一个区县/配送区域编码\"></textarea></label><label>可配送仓库 ID<textarea name=\"warehouseIds\" placeholder=\"每行一个；留空表示所有仓库\"></textarea></label><label>状态<select name=\"status\"><option value=\"active\">启用</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存配送区域</button></form>",
    "<form class=\"card form-card\" id=\"freightForm\"><h3>运费规则</h3><input type=\"hidden\" name=\"id\"><label>规则名称<input name=\"name\" required maxlength=\"80\"></label><label>配送区域<input name=\"deliveryAreaId\" required list=\"deliveryAreaOptions\"></label><datalist id=\"deliveryAreaOptions\"></datalist><label>仓库<input name=\"warehouseId\" list=\"warehouseOptions\" placeholder=\"可留空\"></label><datalist id=\"warehouseOptions\"></datalist><label>基础运费（元）<input name=\"baseFeeCent\" type=\"number\" min=\"0\" value=\"0\"></label><label>附加运费（元）<input name=\"additionalFeeCent\" type=\"number\" min=\"0\" value=\"0\"></label><label>免运门槛（元）<input name=\"freeThresholdCent\" type=\"number\" min=\"0\" value=\"0\"></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"active\">生效</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存运费规则</button></form>",
    "<form class=\"card form-card\" id=\"deliverySlotForm\"><h3>配送时段</h3><input type=\"hidden\" name=\"id\"><label>时段名称<input name=\"name\" required></label><label>配送区域<input name=\"deliveryAreaId\" required list=\"deliveryAreaOptions\"></label><label>仓库<input name=\"warehouseId\" list=\"warehouseOptions\"></label><label>开始时间<input name=\"startTime\" placeholder=\"09:00\" required></label><label>结束时间<input name=\"endTime\" placeholder=\"12:00\" required></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"active\">生效</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存配送时段</button></form>",
    "<form class=\"card form-card\" id=\"groupCampaignForm\"><h3>拼团活动</h3><input type=\"hidden\" name=\"id\"><label>活动标题<input name=\"title\" required></label><label>商品规格<input name=\"skuId\" required list=\"skuOptions\"></label><label>成团人数<input name=\"groupSize\" type=\"number\" min=\"2\" value=\"2\" required></label><label>有效期（分钟）<input name=\"durationMinutes\" type=\"number\" min=\"5\" value=\"120\" required></label><label>拼团单价（元）<input name=\"groupPriceCent\" type=\"number\" min=\"0\" required></label><label>适用用户<select name=\"targetUserType\"><option value=\"all\">全部</option><option value=\"b\">B 端</option><option value=\"c\">C 端</option></select></label><label>状态<select name=\"status\"><option value=\"draft\">草稿</option><option value=\"active\">生效</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存拼团活动</button></form>",
    "<form class=\"card form-card\" id=\"bannerForm\"><h3>轮播图配置</h3><input type=\"hidden\" name=\"id\"><label>标题<input name=\"title\" required maxlength=\"100\"></label><label>素材<input name=\"mediaAssetId\" placeholder=\"从素材库复制\"></label><label>跳转类型<select name=\"jumpType\"><option value=\"none\">无跳转</option><option value=\"product\">商品</option><option value=\"category\">分类</option><option value=\"url\">网页链接</option></select></label><label>跳转目标<input name=\"jumpTarget\" maxlength=\"200\"></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><label class=\"checkbox\"><input name=\"enabled\" type=\"checkbox\" checked>启用</label><button class=\"primary\">保存轮播图</button></form>",
    "<form class=\"card form-card\" id=\"sectionForm\"><h3>新增或修改首页模块</h3><input type=\"hidden\" name=\"id\"><label>模块类型<select name=\"moduleType\"><option value=\"news\">活动头条</option><option value=\"special\">特价专区</option><option value=\"group\">拼团专场</option></select></label><label>标题<input name=\"title\" required maxlength=\"100\"></label><label>副标题<input name=\"subtitle\" maxlength=\"100\" placeholder=\"可留空，使用默认文案\"></label><label>链接文字<input name=\"linkText\" maxlength=\"30\" value=\"更多\"></label><label>素材<input name=\"mediaAssetId\" placeholder=\"从素材库复制\"></label><label>跳转类型<select name=\"jumpType\"><option value=\"none\">无跳转</option><option value=\"product\">商品</option><option value=\"category\">分类</option><option value=\"url\">网页链接</option></select></label><label>跳转目标<input name=\"jumpTarget\" maxlength=\"200\"></label><label>排序<input name=\"sort\" type=\"number\" value=\"0\"></label><label class=\"checkbox\"><input name=\"enabled\" type=\"checkbox\" checked>启用</label><button class=\"primary\">保存首页模块</button></form>",
    "<form class=\"card form-card\" id=\"mediaForm\"><h3>登记素材</h3><input type=\"hidden\" name=\"replacesMediaAssetId\"><p class=\"muted\" id=\"mediaVersionHint\">从电脑选择图片或视频，由后台受控上传；最大 24 MB。替换文件请使用右侧\"新建版本\"，旧素材不会被覆盖。</p><label>素材名称<input name=\"name\" required maxlength=\"100\"></label><label>类型<select name=\"type\"><option value=\"image\">图片</option><option value=\"video\">视频</option></select></label><label>来源<select name=\"source\"><option value=\"client\">甲方提供</option><option value=\"ai_generated\">AI 生成</option><option value=\"demo\">演示素材</option><option value=\"admin_upload\">后台上传</option></select></label><label class=\"checkbox\"><input name=\"temporary\" type=\"checkbox\">临时素材</label><span class=\"muted\">适用端</span><label class=\"checkbox\"><input name=\"targetPlatforms\" type=\"checkbox\" value=\"miniapp\" checked>小程序</label><label class=\"checkbox\"><input name=\"targetPlatforms\" type=\"checkbox\" value=\"web\" checked>网页端</label><label>开始时间（可选）<input name=\"startAt\" type=\"datetime-local\"></label><label>结束时间（可选）<input name=\"endAt\" type=\"datetime-local\"></label><label>选择本地文件<input name=\"uploadFile\" type=\"file\" accept=\"image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime\"></label><button class=\"primary\" type=\"submit\">上传并登记素材</button></form>",
    "<form class=\"card form-card\" id=\"inventoryForm\"><h3>库存调整</h3><p class=\"muted\">每次提交必须携带新的幂等键，重复提交同一键不会重复变更库存。</p><label>仓库<input name=\"warehouseId\" required list=\"warehouseOptions\"></label><label>商品规格<input name=\"skuId\" required list=\"skuOptions\"></label><label>调整数量（正入库，负出库）<input name=\"change\" type=\"number\" required></label><label>调整原因<input name=\"reason\" required maxlength=\"80\"></label><button class=\"primary\">提交库存调整</button></form>",
    "<form class=\"card form-card\" id=\"userPricingForm\"><h3>用户价格身份</h3><p class=\"muted\">企业审核通过后会自动成为 B 端；此处用于受控修正等级或企业归属。</p><label>用户<input name=\"id\" required></label><label>用户类型<select name=\"userType\"><option value=\"c\">C 端</option><option value=\"b\">B 端</option></select></label><label>企业<input name=\"organizationId\" placeholder=\"B 端必填\"></label><label>价格等级<input name=\"priceLevel\" placeholder=\"例如 b_standard\"></label><button class=\"primary\">保存身份与价格等级</button></form>",
  ];
  const areaVariant = "<form class=\"card form-card\" id=\"deliveryAreaForm\"><h3>配送区域</h3><input type=\"hidden\" name=\"id\"><label>区域名称<input name=\"name\" required maxlength=\"80\"></label><label>区域编码（由「选择区域」按钮自动维护）<textarea name=\"regionCodes\" style=\"display:none\"></textarea></label><label>可配送仓库 ID<textarea name=\"warehouseIds\" placeholder=\"每行一个；留空表示所有仓库\"></textarea></label><label>状态<select name=\"status\"><option value=\"active\">启用</option><option value=\"disabled\">停用</option></select></label><button class=\"primary\">保存配送区域</button></form>";
  const root = document.querySelector('.hidden-forms');
  if (!root) return;
  if (global.PAGE_NAME === 'areas') {
    const index = forms.findIndex((form) => form.includes('id="deliveryAreaForm"'));
    if (index >= 0) forms[index] = areaVariant;
  }
  root.innerHTML = forms.join('\n');
}(window, document));
