const assert = require('assert/strict');
const marketing = require('../lib/marketing');
const { buildQuote, createOrder, cancelOrder } = require('../lib/commerce');
const { requestRefund } = require('../lib/refunds');
const { inventoryId } = require('../lib/transaction-ids');
const { createApplication } = require('../app');
const { awardOrderPoints, reverseRefundPoints } = require('../lib/points');
const { stableDocumentId } = require('../lib/transaction-ids');

function memoryStore() {
  const data = new Map(); let n = 0; let tail = Promise.resolve(); const rows = (c) => data.get(c) || []; const matches = (x, w = {}) => Object.entries(w).every(([k, v]) => x[k] === v);
  const store = { async getById(c, id) { return rows(c).find((x) => x._id === id) || null; }, async findOne(c, w) { return rows(c).find((x) => matches(x, w)) || null; }, async list(c, o = {}) { let out = rows(c).filter((x) => matches(x, o.where)); (o.orderBy || []).slice().reverse().forEach(({ field, direction }) => { out = out.slice().sort((a, b) => direction === 'desc' ? String(b[field] || '').localeCompare(String(a[field] || '')) : String(a[field] || '').localeCompare(String(b[field] || ''))); }); const page = o.page || 1; const pageSize = o.pageSize || 20; return { rows: out.slice((page - 1) * pageSize, page * pageSize), total: out.length, page, pageSize }; }, async create(c, x) { const row = { ...x, _id: x._id || `${c}-${++n}` }; data.set(c, [...rows(c), row]); return row; }, async set(c, id, x) { const row = { ...x, _id: id }; data.set(c, rows(c).some((v) => v._id === id) ? rows(c).map((v) => v._id === id ? row : v) : [...rows(c), row]); return row; }, async update(c, id, p) { data.set(c, rows(c).map((v) => v._id === id ? { ...v, ...p } : v)); }, async remove(c, id) { data.set(c, rows(c).filter((v) => v._id !== id)); }, async runTransaction(work) { let release; const prior = tail; tail = new Promise((resolve) => { release = resolve; }); await prior; try { return await work({ getById: store.getById, set: store.set, update: store.update, remove: store.remove }); } finally { release(); } } }; return store;
}
async function errorCode(work) { try { await work(); return ''; } catch (error) { return error.code; } }

async function run() {
  const store = memoryStore(); const now = new Date('2026-09-12T00:00:00.000Z'); const user = { _id: 'u1', userType: 'c', businessStatus: '' }; const admin = { _id: 'a1' };
  await store.create('products', { _id: 'p1', name: '商品1', categoryId: 'c1', status: 'on_sale' }); await store.create('products', { _id: 'p2', name: '商品2', categoryId: 'c2', status: 'on_sale' });
  await store.create('product_skus', { _id: 's1', productId: 'p1', specName: 'A', packageUnit: '件', status: 'on_sale' }); await store.create('product_skus', { _id: 's2', productId: 'p2', specName: 'B', packageUnit: '件', status: 'on_sale' });
  await store.create('prices', { _id: 'pr1', skuId: 's1', scopeType: 'public', amountCent: 101, status: 'active' }); await store.create('prices', { _id: 'pr2', skuId: 's2', scopeType: 'public', amountCent: 99, status: 'active' });
  await store.create('warehouses', { _id: 'w1', status: 'active' }); await store.create('inventory', { _id: inventoryId('w1', 's1'), warehouseId: 'w1', skuId: 's1', onHand: 100, reserved: 0, available: 100 }); await store.create('inventory', { _id: inventoryId('w1', 's2'), warehouseId: 'w1', skuId: 's2', onHand: 100, reserved: 0, available: 100 });
  await store.create('delivery_areas', { _id: 'da1', status: 'active', regionCodes: ['r1'], warehouseIds: ['w1'] }); await store.create('freight_rules', { _id: 'fr1', status: 'active', warehouseId: 'w1', deliveryAreaId: 'da1', baseFeeCent: 50, additionalFeeCent: 0 }); await store.create('addresses', { _id: 'addr1', userId: 'u1', status: 'active', regionCode: 'r1', name: 'U' });

  assert.equal(await errorCode(() => marketing.adminBundleUpsert({ store, admin, payload: { name: 'AI', items: [{ skuId: 's1', quantity: 1 }], bundlePriceCent: 90, status: 'active', source: 'ai_generated', temporary: true }, now })), 'DRAFT_CANNOT_ACTIVATE');
  const bundle = await marketing.adminBundleUpsert({ store, admin, payload: { name: '正式套餐', items: [{ skuId: 's1', quantity: 1 }, { skuId: 's2', quantity: 1 }], bundlePriceCent: 151, status: 'active', source: 'client', temporary: false }, now });
  const template = await marketing.adminCouponUpsert({ store, admin, payload: { name: '分类券', type: 'fixed', discountCent: 20, minSpendCent: 50, scopeType: 'category', scopeIds: ['c1'], totalLimit: 1, perUserLimit: 1, status: 'active', source: 'client', temporary: false }, now });
  const [claimA, claimB] = await Promise.all([marketing.couponClaim({ store, user, payload: { templateId: template._id, idempotencyKey: 'claim-a' }, now }), marketing.couponClaim({ store, user, payload: { templateId: template._id, idempotencyKey: 'claim-b' }, now }).catch((e) => e)]); assert.ok(claimA.coupon); assert.equal(claimB.code, 'COUPON_SOLD_OUT');
  const quote = await buildQuote({ store, user, warehouseId: 'w1', regionCode: 'r1', items: [], now, bundleId: bundle._id, bundleQuantity: 1, couponId: claimA.coupon._id });
  assert.equal(quote.goodsAmountCent, 151); assert.equal(quote.discountAmountCent, 20); assert.equal(quote.items.reduce((sum, x) => sum + x.paidSubtotalCent, 0), 131, '净商品金额必须按项完整分摊'); assert.equal(quote.payableAmountCent, 181);
  const created = await createOrder({ store, user, payload: { idempotencyKey: 'order-1', warehouseId: 'w1', addressId: 'addr1', fulfillmentType: 'delivery', paymentMethod: 'demo', bundleId: bundle._id, bundleQuantity: 1, couponId: claimA.coupon._id }, now });
  assert.equal(created.order.itemsSnapshot.reduce((sum, x) => sum + x.refundableAmountCent, 0), 131); assert.equal((await store.getById('user_coupons', claimA.coupon._id)).status, 'used');
  await cancelOrder({ store, user, orderId: created.order._id, now }); assert.equal((await store.getById('user_coupons', claimA.coupon._id)).status, 'available', '取消建单必须释放优惠券');

  const paidItems = [{ _id: 'oi1', orderItemId: 'oi1', skuId: 's1', productId: 'p1', quantity: 3, unitPriceCent: 100, subtotalCent: 300, paidSubtotalCent: 200, refundableAmountCent: 200 }];
  await store.create('orders', { _id: 'paid-order', userId: 'u1', status: 'completed', paymentStatus: 'paid', totalAmountCent: 250, refundedAmountCent: 0, itemIds: ['oi1'], itemsSnapshot: paidItems, createdAt: now.toISOString(), completedAt: now.toISOString() });
  const first = await requestRefund({ store, user, payload: { orderId: 'paid-order', items: [{ orderItemId: 'oi1', quantity: 1 }], reasonCode: 'other', idempotencyKey: 'r1' }, now }); assert.equal(first.refund.amountCent, 66);
  await store.update('orders', 'paid-order', { activeRefundId: '', refundedAmountCent: 66 });
  const second = await requestRefund({ store, user, payload: { orderId: 'paid-order', items: [{ orderItemId: 'oi1', quantity: 2 }], reasonCode: 'other', idempotencyKey: 'r2' }, now }); assert.equal(second.refund.goodsAmountCent, 134, '最后数量必须吸收分摊尾差'); assert.equal(second.refund.amountCent, 184, '全选剩余商品时才计入剩余运费');

  await store.create('orders', { _id: 'review-order', userId: 'u1', status: 'completed', itemIds: ['review-item'], itemsSnapshot: [{ orderItemId: 'review-item', productId: 'p1', skuId: 's1', quantity: 1 }] });
  await marketing.reviewCreate({ store, user, payload: { orderId: 'review-order', orderItemId: 'review-item', rating: 5, idempotencyKey: 'review-1' }, now }); assert.equal(await errorCode(() => marketing.reviewCreate({ store, user, payload: { orderId: 'review-order', orderItemId: 'review-item', rating: 4, idempotencyKey: 'review-2' }, now })), 'REVIEW_ALREADY_EXISTS');
  const before = await marketing.storedAccount({ store, user }); await marketing.topupIntent({ store, user, payload: { amountCent: 1000, idempotencyKey: 'topup-1' }, now }); const after = await marketing.storedAccount({ store, user }); assert.equal(after.account.balanceCent, before.account.balanceCent, '充值意向不得增加余额');
  await store.set('points_rules', stableDocumentId('points_rule', ['order_reward']), { code: 'order_reward', pointsPerYuan: 2, status: 'active', source: 'client', temporary: false }); const pointsOrder = { _id: 'points-order', userId: 'u1', totalAmountCent: 550 }; await store.runTransaction((tx) => awardOrderPoints(tx, pointsOrder, now)); await store.runTransaction((tx) => awardOrderPoints(tx, pointsOrder, now)); assert.equal((await marketing.pointsAccount({ store, user })).account.balance, 10, '订单积分奖励必须幂等'); await store.runTransaction((tx) => reverseRefundPoints(tx, pointsOrder, { _id: 'points-refund' }, 275, now)); await store.runTransaction((tx) => reverseRefundPoints(tx, pointsOrder, { _id: 'points-refund' }, 275, now)); assert.equal((await marketing.pointsAccount({ store, user })).account.balance, 5, '退款扣回必须幂等且余额不为负');

  const secureStore = memoryStore(); const app = createApplication({ store: secureStore, getIdentity: () => ({ OPENID: 'invoice-user' }), bootstrapToken: 'boot', piiEncryptionKey: 'marketing-test-pii-key', clock: () => now, storageUploader: async () => 'cloud://review/image.png', mediaUrlResolver: async (ids) => Object.fromEntries(ids.map((id) => [id, `https://cdn.test/${id}`])) });
  const call = (action, payload = {}) => app.dispatch({ action, payload }); const me = await call('auth.me'); const secureUserId = me.data.user._id;
  const title = await call('invoiceTitles.upsert', { type: 'company', name: '测试公司', taxNo: '91340000123456789X', bankName: '测试银行', bankAccount: '6222000012345678' }); assert.equal(title.data.title.taxNo, '91340000123456789X'); const storedTitle = await secureStore.getById('invoice_titles', title.data.title._id); assert.equal(Object.hasOwn(storedTitle, 'taxNo'), false); assert.notEqual(storedTitle.taxNoCiphertext, '91340000123456789X');
  await secureStore.create('orders', { _id: 'invoice-order', userId: secureUserId, status: 'completed', paymentStatus: 'paid', totalAmountCent: 1000 }); await call('invoices.request', { orderId: 'invoice-order', titleId: title.data.title._id, idempotencyKey: 'invoice-1' });
  await call('admin.bootstrap', { bootstrapToken: 'boot', username: 'owner', password: '1234567890ab' }); const login = await call('admin.login', { username: 'owner', password: '1234567890ab' }); const adminList = await call('admin.invoices.list', { adminToken: login.data.token }); assert.equal(Object.hasOwn(adminList.data.rows[0].titleSnapshot, 'taxNo'), false); assert.match(adminList.data.rows[0].titleSnapshot.taxNoMasked, /\*{4,}/);
  const upload = await call('reviews.media.upload', { type: 'image', fileName: 'show.png', mimeType: 'image/png', contentBase64: Buffer.from('review').toString('base64') }); await secureStore.create('orders', { _id: 'secure-review-order', userId: secureUserId, status: 'completed', itemIds: ['secure-item'], itemsSnapshot: [{ orderItemId: 'secure-item', productId: 'p1', skuId: 's1', quantity: 1 }] }); const review = await call('reviews.create', { orderId: 'secure-review-order', orderItemId: 'secure-item', rating: 5, mediaIds: [upload.data.mediaId], idempotencyKey: 'secure-review' }); assert.equal((await call('content.media.resolve', { ids: [upload.data.mediaId], platform: 'web' })).data.rows.length, 0, '未审核晒单媒体不得公开'); await call('admin.reviews.review', { adminToken: login.data.token, id: review.data.review._id, decision: 'approved' }); assert.equal((await call('content.media.resolve', { ids: [upload.data.mediaId], platform: 'web' })).data.rows[0].url, `https://cdn.test/cloud://review/image.png`);
  console.log('marketing and membership tests: passed');
}
run().catch((error) => { console.error(error); process.exit(1); });
