const assert = require('assert/strict');
const { createApplication } = require('../app');

function memoryStore() {
  const data = new Map(); let n = 0; let tail = Promise.resolve(); const rows = (c) => data.get(c) || []; const match = (x, w = {}) => Object.entries(w).every(([k, v]) => x[k] === v);
  const store = { async getById(c, id) { return rows(c).find((x) => x._id === id) || null; }, async findOne(c, w) { return rows(c).find((x) => match(x, w)) || null; }, async list(c, o = {}) { let out = rows(c).filter((x) => match(x, o.where)); const page = o.page || 1; const pageSize = o.pageSize || 20; return { rows: out.slice((page - 1) * pageSize, page * pageSize), total: out.length, page, pageSize }; }, async create(c, x) { const row = { ...x, _id: x._id || `${c}-${++n}` }; data.set(c, [...rows(c), row]); return row; }, async set(c, id, x) { const row = { ...x, _id: id }; data.set(c, rows(c).some((v) => v._id === id) ? rows(c).map((v) => v._id === id ? row : v) : [...rows(c), row]); return row; }, async update(c, id, p) { data.set(c, rows(c).map((v) => v._id === id ? { ...v, ...p } : v)); return { _id: id, ...p }; }, async remove(c, id) { data.set(c, rows(c).filter((v) => v._id !== id)); }, async runTransaction(work) { let release; const prior = tail; tail = new Promise((resolve) => { release = resolve; }); await prior; try { return await work({ getById: store.getById, set: store.set, update: store.update, remove: store.remove }); } finally { release(); } } }; return store;
}
async function run() {
  const store = memoryStore(); let time = new Date('2026-09-12T00:00:00.000Z'); const app = createApplication({ store, getIdentity: () => ({ OPENID: 'mini-openid' }), bootstrapToken: 'boot', piiEncryptionKey: 'web-auth-test-pii', clock: () => time }); const call = (action, payload = {}) => app.dispatch({ action, payload });
  await store.create('users', { _id: 'u1', openid: 'wx-u1', userType: 'c', status: 'active' }); await store.create('users', { _id: 'u2', openid: 'wx-u2', userType: 'b', businessStatus: 'approved', organizationId: 'org2', status: 'active' }); await store.create('cart_items', { _id: 'c1', userId: 'u1', skuId: 's1', quantity: 1 }); await store.create('cart_items', { _id: 'c2', userId: 'u2', skuId: 's2', quantity: 2 });
  await call('admin.bootstrap', { bootstrapToken: 'boot', username: 'owner', password: '1234567890ab' }); const admin = await call('admin.login', { username: 'owner', password: '1234567890ab' }); const adminToken = admin.data.token;
  const a1 = await call('admin.webAccounts.upsert', { adminToken, userId: 'u1', loginId: 'user-one', password: 'password-one' }); const a2 = await call('admin.webAccounts.upsert', { adminToken, userId: 'u2', loginId: '13800000002', password: 'password-two' }); assert.equal(Object.hasOwn(a1.data.account, 'passwordHash'), false); assert.equal(Object.hasOwn(a1.data.account, 'salt'), false);
  const l1 = await call('auth.web.login', { loginId: 'user-one', password: 'password-one' }); const l2 = await call('auth.webLogin', { phone: '13800000002', password: 'password-two' }); assert.equal(l1.ok, true); assert.equal(l2.ok, true); assert.notEqual(l1.data.sessionToken, l2.data.sessionToken); const storedSession = await store.findOne('web_user_sessions', { userId: 'u1' }); assert.notEqual(storedSession.tokenHash, l1.data.sessionToken); assert.equal(Object.hasOwn(storedSession, 'sessionToken'), false);
  const [cart1, cart2] = await Promise.all([call('cart.list', { sessionToken: l1.data.sessionToken, userId: 'u2', openid: 'wx-u2' }), call('cart.list', { sessionToken: l2.data.sessionToken, userId: 'u1', openid: 'wx-u1' })]); assert.deepEqual(cart1.data.rows.map((x) => x._id), ['c1']); assert.deepEqual(cart2.data.rows.map((x) => x._id), ['c2']); assert.equal((await call('auth.me', { sessionToken: l2.data.sessionToken, userId: 'u1' })).data.user._id, 'u2');
  assert.equal((await call('auth.me', { webSessionToken: l1.data.sessionToken })).data.user._id, 'u1', '旧网页字段仅作同值兼容'); assert.equal((await call('auth.me', { sessionToken: l1.data.sessionToken, webSessionToken: l2.data.sessionToken })).error.code, 'AUTH_TOKEN_CONFLICT');
  await store.create('bundles', { _id: 'public-bundle', name: '匿名套餐', items: [{ skuId: 's1', quantity: 1 }], bundlePriceCent: 1, status: 'active', source: 'client', temporary: false }); const anonymousBundle = await call('bundles.get', { id: 'public-bundle' }); assert.equal(Object.hasOwn(anonymousBundle.data.bundle, 'bundlePriceCent'), false, '匿名套餐详情不得泄露金额');
  await call('auth.web.logout', { sessionToken: l1.data.sessionToken }); assert.equal((await call('cart.list', { sessionToken: l1.data.sessionToken })).error.code, 'AUTH_SESSION_EXPIRED');
  const changed = await call('auth.web.password.change', { sessionToken: l2.data.sessionToken, currentPassword: 'password-two', newPassword: 'password-new-two' }); assert.equal(changed.data.reloginRequired, true); assert.equal((await call('auth.web.me', { sessionToken: l2.data.sessionToken })).error.code, 'AUTH_SESSION_EXPIRED'); const relogin = await call('auth.web.login', { loginId: '13800000002', password: 'password-new-two' }); assert.equal(relogin.ok, true);
  await call('admin.webAccounts.setStatus', { adminToken, id: a2.data.account._id, status: 'disabled' }); assert.equal((await call('auth.web.me', { sessionToken: relogin.data.sessionToken })).error.code, 'AUTH_ACCOUNT_DISABLED'); assert.equal((await call('auth.web.login', { loginId: '13800000002', password: 'password-new-two' })).error.code, 'AUTH_ACCOUNT_DISABLED');
  for (let attempt = 0; attempt < 4; attempt += 1) assert.equal((await call('auth.web.login', { loginId: 'user-one', password: 'wrong-password' })).error.code, 'AUTH_INVALID_CREDENTIALS'); assert.equal((await call('auth.web.login', { loginId: 'user-one', password: 'wrong-password' })).error.code, 'AUTH_ACCOUNT_LOCKED'); assert.equal((await call('auth.web.login', { loginId: 'user-one', password: 'password-one' })).error.code, 'AUTH_ACCOUNT_LOCKED');
  await call('admin.webAccounts.resetPassword', { adminToken, id: a1.data.account._id, newPassword: 'reset-password' }); const resetLogin = await call('auth.web.login', { loginId: 'user-one', password: 'reset-password' }); assert.equal(resetLogin.ok, true); const resetResult = await call('admin.webAccounts.resetPassword', { adminToken, id: a1.data.account._id, newPassword: 'another-password' }); assert.equal(Object.hasOwn(resetResult.data, 'password'), false); assert.equal(Object.hasOwn(resetResult.data.account, 'passwordHash'), false);
  const expiring = await call('auth.web.login', { loginId: 'user-one', password: 'another-password' }); const expiringRecord = await store.findOne('web_user_sessions', { tokenHash: require('../lib/security').sha256(expiring.data.sessionToken) }); await store.update('web_user_sessions', expiringRecord._id, { expiresAt: '2026-09-11T00:00:00.000Z' }); assert.equal((await call('auth.web.me', { sessionToken: expiring.data.sessionToken })).error.code, 'AUTH_SESSION_EXPIRED');
  const mini = await call('auth.wechatLogin', { sessionToken: 'forged-token', userId: 'u1' }); assert.equal(mini.data.user.openid, undefined); assert.notEqual(mini.data.user._id, 'u1', '小程序登录只信任 OPENID，不信任 payload 身份。');
  const firstLoginStore = memoryStore(); const firstLoginApp = createApplication({ store: firstLoginStore, getIdentity: () => ({ OPENID: 'same-first-openid' }), clock: () => time }); const firstLogins = await Promise.all(Array.from({ length: 20 }, () => firstLoginApp.dispatch({ action: 'auth.wechatLogin', payload: {} }))); assert.equal(new Set(firstLogins.map((result) => result.data.user._id)).size, 1, '同 OPENID 并发首次登录必须返回同一 userId'); assert.equal((await firstLoginStore.list('users', { where: { openid: 'same-first-openid' }, page: 1, pageSize: 100 })).total, 1, '同 OPENID 只能落一条用户记录');
  await firstLoginStore.create('products', { _id: 'cart-product', status: 'on_sale', audienceType: 'all' }); await firstLoginStore.create('product_skus', { _id: 'cart-sku', productId: 'cart-product', status: 'on_sale' }); const concurrentCartWrites = await Promise.all(Array.from({ length: 20 }, (_, index) => firstLoginApp.dispatch({ action: 'cart.upsert', payload: { skuId: 'cart-sku', quantity: index + 1 } }))); assert.equal(concurrentCartWrites.every((result) => result.ok), true); const firstUserId = firstLogins[0].data.user._id; assert.equal((await firstLoginStore.list('cart_items', { where: { userId: firstUserId, skuId: 'cart-sku' }, page: 1, pageSize: 100 })).total, 1, '同用户同 SKU 并发首次加dbo物车只能落一行');
  const legacyStore = memoryStore(); await legacyStore.create('users', { _id: 'legacy-user-id', openid: 'legacy-openid', userType: 'b', status: 'active' }); const legacyApp = createApplication({ store: legacyStore, getIdentity: () => ({ OPENID: 'legacy-openid' }), clock: () => time }); const legacyLogin = await legacyApp.dispatch({ action: 'auth.wechatLogin', payload: {} }); assert.equal(legacyLogin.data.user._id, 'legacy-user-id', '已有 openid 用户必须保留历史 userId');
  console.log('web user session tests: passed');
}
run().catch((error) => { console.error(error); process.exit(1); });
