const assert = require('assert/strict');
const { createApplication } = require('../app');
const { inventoryId } = require('../lib/transaction-ids');

function memoryStore() {
  const data = new Map(); let n = 0; let tail = Promise.resolve(); const rows = (c) => data.get(c) || []; const match = (x, w = {}) => Object.entries(w).every(([k, v]) => x[k] === v);
  const store = { async getById(c, id) { return rows(c).find((x) => x._id === id) || null; }, async findOne(c, w) { return rows(c).find((x) => match(x, w)) || null; }, async list(c, o = {}) { let out = rows(c).filter((x) => match(x, o.where)); const page = o.page || 1; const pageSize = o.pageSize || 20; return { rows: out.slice((page - 1) * pageSize, page * pageSize), total: out.length, page, pageSize }; }, async create(c, x) { const row = { ...x, _id: x._id || `${c}-${++n}` }; data.set(c, [...rows(c), row]); return row; }, async set(c, id, x) { const row = { ...x, _id: id }; data.set(c, rows(c).some((v) => v._id === id) ? rows(c).map((v) => v._id === id ? row : v) : [...rows(c), row]); return row; }, async update(c, id, p) { data.set(c, rows(c).map((v) => v._id === id ? { ...v, ...p } : v)); return { _id: id, ...p }; }, async remove(c, id) { data.set(c, rows(c).filter((v) => v._id !== id)); }, async runTransaction(work) { let release; const prior = tail; tail = new Promise((resolve) => { release = resolve; }); await prior; try { return await work({ getById: store.getById, set: store.set, update: store.update, remove: store.remove }); } finally { release(); } } }; return store;
}
async function run() {
  const store = memoryStore(); const now = new Date('2026-09-12T00:00:00.000Z'); const app = createApplication({ store, getIdentity: () => ({}), bootstrapToken: 'boot', piiEncryptionKey: 'web-commerce-pii-key', demoMode: true, clock: () => now }); const call = (action, payload = {}) => app.dispatch({ action, payload });
  await store.create('users', { _id: 'web-u1', userType: 'c', status: 'active' }); await store.create('users', { _id: 'web-u2', userType: 'c', status: 'active' }); await call('admin.bootstrap', { bootstrapToken: 'boot', username: 'owner', password: '1234567890ab' }); const admin = await call('admin.login', { username: 'owner', password: '1234567890ab' }); const adminToken = admin.data.token; await call('admin.webAccounts.upsert', { adminToken, userId: 'web-u1', loginId: 'buyer-one', password: 'password-one' }); await call('admin.webAccounts.upsert', { adminToken, userId: 'web-u2', loginId: 'buyer-two', password: 'password-two' }); const login = await call('auth.web.login', { loginId: 'buyer-one', password: 'password-one' }); const sessionToken = login.data.sessionToken;
  await store.update('users', 'web-u1', { organizationId: '' }); await store.update('users', 'web-u2', { organizationId: '' });
  const login2 = await call('auth.web.login', { loginId: 'buyer-two', password: 'password-two' }); const sessionToken2 = login2.data.sessionToken;
  await store.create('products', { _id: 'p1', name: '网页商品', categoryId: 'cat1', status: 'on_sale', audienceType: 'all' }); await store.create('product_skus', { _id: 's1', productId: 'p1', specName: '整箱', packageUnit: '箱', minOrderQuantity: 2, orderMultiple: 2, status: 'on_sale' }); await store.create('prices', { _id: 'price-web', skuId: 's1', scopeType: 'public', channel: 'web', amountCent: 100, status: 'active' }); await store.create('warehouses', { _id: 'w1', name: '网页仓', status: 'active' }); await store.create('inventory', { _id: inventoryId('w1', 's1'), warehouseId: 'w1', skuId: 's1', onHand: 50, reserved: 0, available: 50 }); await store.create('delivery_areas', { _id: 'area1', name: '配送区', regionCodes: ['r1'], warehouseIds: ['w1'], status: 'active' }); await store.create('freight_rules', { _id: 'freight1', warehouseId: 'w1', deliveryAreaId: 'area1', baseFeeCent: 30, additionalFeeCent: 0, status: 'active' }); await store.create('delivery_slots', { _id: 'slot1', name: '下午', warehouseId: 'w1', deliveryAreaId: 'area1', status: 'active' }); await store.create('pickup_sites', { _id: 'pickup1', name: '自提点', address: '仓1号门', regionCode: 'r1', warehouseId: 'w1', status: 'active' }); await store.create('addresses', { _id: 'addr1', userId: 'web-u1', name: '买家1', regionCode: 'r1', detail: '地址1', status: 'active' }); await store.create('addresses', { _id: 'addr2', userId: 'web-u2', name: '买家2', regionCode: 'r1', detail: '地址2', status: 'active' });
  const delivery = await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'delivery', addressId: 'addr1', deliverySlotId: 'slot1', items: [{ skuId: 's1', quantity: 2 }] }); assert.equal(delivery.data.quote.freightAmountCent, 30); assert.equal(delivery.data.quote.deliverySlot.id, 'slot1'); assert.equal((await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'delivery', addressId: 'addr2', items: [{ skuId: 's1', quantity: 2 }] })).error.code, 'ADDRESS_NOT_AVAILABLE', '网页会话不得使用他人地址');
  const pickup = await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', items: [{ skuId: 's1', quantity: 2 }] }); assert.equal(pickup.data.quote.freightAmountCent, 0); assert.equal(pickup.data.quote.pickupSiteSnapshot.id, 'pickup1'); assert.equal((await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', deliverySlotId: 'slot1', items: [{ skuId: 's1', quantity: 2 }] })).error.code, 'DELIVERY_SLOT_NOT_AVAILABLE');
  await store.create('bundles', { _id: 'bundle1', name: '网页套餐', items: [{ skuId: 's1', quantity: 2 }], bundlePriceCent: 150, version: 1, status: 'active', source: 'client', temporary: false }); await store.create('coupon_templates', { _id: 'tpl1', name: '网页券', type: 'fixed', discountCent: 10, minSpendCent: 1, scopeType: 'all', version: 1, status: 'active', source: 'client', temporary: false }); await store.create('user_coupons', { _id: 'coupon1', templateId: 'tpl1', userId: 'web-u1', status: 'available' }); const promoted = await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', bundleId: 'bundle1', bundleQuantity: 1, couponId: 'coupon1' }); assert.equal(promoted.data.quote.payableAmountCent, 140); assert.equal(promoted.data.quote.bundleSnapshot.id, 'bundle1'); assert.equal(promoted.data.quote.couponSnapshot.userCouponId, 'coupon1');
  await store.create('accepted_quote_tokens', { _id: 'quote-token', userId: 'web-u1', organizationId: '', quoteId: 'quote1', version: 1, validUntil: '2026-09-13T00:00:00.000Z', status: 'active', items: [{ skuId: 's1', quantity: 2, unitPriceCent: 80 }] }); const inquiryQuote = await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', acceptedQuoteToken: 'quote-token', items: [{ skuId: 's1', quantity: 2 }] }); assert.equal(inquiryQuote.data.quote.goodsAmountCent, 160); assert.equal((await call('checkout.quote', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', acceptedQuoteToken: 'quote-token', bundleId: 'bundle1', bundleQuantity: 1 })).error.code, 'PROMOTION_CONFLICT');
  assert.equal((await call('checkout.quote', { sessionToken: sessionToken2, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', acceptedQuoteToken: 'quote-token', items: [{ skuId: 's1', quantity: 2 }] })).error.code, 'INQUIRY_QUOTE_FORBIDDEN'); assert.equal((await call('checkout.quote', { sessionToken: sessionToken2, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', couponId: 'coupon1', items: [{ skuId: 's1', quantity: 2 }] })).error.code, 'COUPON_NOT_AVAILABLE');
  const created = await call('orders.create', { sessionToken, channel: 'web', warehouseId: 'w1', fulfillmentType: 'pickup', pickupSiteId: 'pickup1', paymentMethod: 'demo', bundleId: 'bundle1', bundleQuantity: 1, couponId: 'coupon1', idempotencyKey: 'web-order-1' }); assert.equal(created.ok, true); assert.equal(created.data.order.totalAmountCent, 140); assert.equal(created.data.order.addressSnapshot, null); const replay = await call('orders.create', { sessionToken, idempotencyKey: 'web-order-1' }); assert.equal(replay.data.idempotent, true); assert.equal(replay.data.order._id, created.data.order._id);
  console.log('web commerce server contract tests: passed');
}
run().catch((error) => { console.error(error); process.exit(1); });
