const { fail } = require('./response');
const { stableDocumentId } = require('./transaction-ids');
const { buildQuote } = require('./commerce');
const { collectPageMatches } = require('./collection-read');
function i(v, d = 0) { const n = Number(v); return Number.isInteger(n) ? n : d; }
function pg(p = {}) { return { page: Math.max(1, i(p.page, 1)), pageSize: Math.min(100, Math.max(1, i(p.pageSize, 20))) }; }
function sched(x, now) { return x && x.status === 'active' && x.temporary !== true && x.source !== 'ai_generated' && (!x.validFrom || new Date(x.validFrom) <= now) && (!x.validTo || new Date(x.validTo) > now); }
async function list(store, c, where, payload) { return store.list(c, { where, orderBy: [{ field: 'createdAt', direction: 'desc' }], allowMissingCollection: true, ...pg(payload) }); }
async function filteredPage(store, collection, options, predicate, payload) { const paging = pg(payload); const rows = await collectPageMatches(store, collection, options, predicate, { pageSize: 100, maxPages: 50 }); const start = (paging.page - 1) * paging.pageSize; return { rows: rows.slice(start, start + paging.pageSize), total: rows.length, ...paging }; }
async function bundleList({ store, payload, now }) { const result = await filteredPage(store, 'bundles', { where: { status: 'active' }, orderBy: [{ field: 'createdAt', direction: 'desc' }], allowMissingCollection: true }, (x) => sched(x, now), payload); return { ...result, rows: result.rows.map(bundleSafe) }; }
function bundleSafe(x) { return { _id: x._id, name: x.name, description: x.description || '', items: x.items || [], status: x.status, source: x.source, temporary: x.temporary === true, validFrom: x.validFrom || '', validTo: x.validTo || '', createdAt: x.createdAt, updatedAt: x.updatedAt }; }
async function bundleGet({ store, payload, now }) { const x = await store.getById('bundles', String(payload.id || payload.bundleId || '')); if (!sched(x, now)) fail('BUNDLE_NOT_AVAILABLE', '套餐不存在或不可用。'); return { bundle: bundleSafe(x) }; }
async function bundleQuote({ store, user, payload, now }) { return { quote: await buildQuote({ store, user, warehouseId: String(payload.warehouseId || ''), regionCode: String(payload.regionCode || ''), items: [], channel: payload.channel, now, fulfillmentType: payload.fulfillmentType, pickupSiteId: payload.pickupSiteId, bundleId: String(payload.bundleId || ''), bundleQuantity: i(payload.quantity, 0), couponId: String(payload.couponId || '') }) }; }
async function adminBundleUpsert({ store, admin, payload, now }) { const items = Array.isArray(payload.items) ? payload.items.slice(0, 20).map((x) => ({ skuId: String(x.skuId || ''), quantity: i(x.quantity) })) : []; if (!items.length || items.some((x) => !x.skuId || x.quantity < 1) || new Set(items.map((x) => x.skuId)).size !== items.length) fail('BUNDLE_ITEMS_INVALID', '套餐商品不合法。'); for (const x of items) if (!await store.getById('product_skus', x.skuId)) fail('SKU_NOT_FOUND', '套餐商品规格不存在。'); const source = ['client', 'ai_generated'].includes(payload.source) ? payload.source : 'ai_generated'; const temporary = payload.temporary !== false; const status = ['draft', 'active', 'disabled'].includes(payload.status) ? payload.status : 'draft'; if (status === 'active' && (temporary || source === 'ai_generated')) fail('DRAFT_CANNOT_ACTIVATE', 'AI 或临时套餐草案不能启用。'); const id = String(payload.id || stableDocumentId('bundle', [String(payload.name || ''), now.toISOString()])); const old = await store.getById('bundles', id); const row = { _id: id, name: String(payload.name || '').slice(0, 100), description: String(payload.description || '').slice(0, 500), items, bundlePriceCent: i(payload.bundlePriceCent), status, source, temporary, version: i(old && old.version, 0) + 1, validFrom: String(payload.validFrom || ''), validTo: String(payload.validTo || ''), updatedBy: admin._id, createdAt: old && old.createdAt || now.toISOString(), updatedAt: now.toISOString() }; if (!row.name || row.bundlePriceCent < 1) fail('VALIDATION_ERROR', '套餐名称或价格不合法。'); await store.set('bundles', id, row); return row; }

async function couponTemplates({ store, payload, now }) { return filteredPage(store, 'coupon_templates', { where: { status: 'active' }, orderBy: [{ field: 'createdAt', direction: 'desc' }], allowMissingCollection: true }, (x) => sched(x, now), payload); }
async function couponClaim({ store, user, payload, now }) { const templateId = String(payload.templateId || ''); const key = String(payload.idempotencyKey || ''); if (!key) fail('IDEMPOTENCY_KEY_REQUIRED', '领取优惠券需要幂等键。'); const id = stableDocumentId('ucoupon', [user._id, key]); return store.runTransaction(async (tx) => { const old = await tx.getById('user_coupons', id); if (old) return { coupon: old, idempotent: true }; const t = await tx.getById('coupon_templates', templateId); if (!sched(t, now)) fail('COUPON_NOT_AVAILABLE', '优惠券不可领取。'); const counterId = stableDocumentId('couponcounter', [templateId]); const counter = await tx.getById('coupon_counters', counterId) || { claimed: 0, byUser: {} }; if (counter.claimed >= i(t.totalLimit, 0) && i(t.totalLimit, 0) > 0) fail('COUPON_SOLD_OUT', '优惠券已领完。'); if (i(counter.byUser[user._id], 0) >= Math.max(1, i(t.perUserLimit, 1))) fail('COUPON_USER_LIMIT', '已达到每人限领数量。'); const coupon = { _id: id, templateId, userId: user._id, status: 'available', snapshot: t, validTo: t.validTo || '', idempotencyKey: key, createdAt: now.toISOString(), updatedAt: now.toISOString() }; await tx.set('user_coupons', id, coupon); await tx.set('coupon_counters', counterId, { _id: counterId, templateId, claimed: counter.claimed + 1, byUser: { ...counter.byUser, [user._id]: i(counter.byUser[user._id]) + 1 }, updatedAt: now.toISOString() }); return { coupon, idempotent: false }; }); }
async function couponList({ store, user, payload, now }) { return filteredPage(store, 'user_coupons', { where: { userId: user._id }, orderBy: [{ field: 'createdAt', direction: 'desc' }], allowMissingCollection: true }, (x) => !x.validTo || new Date(x.validTo) > now, payload); }
async function adminCouponUpsert({ store, admin, payload, now }) { const type = ['fixed', 'percent'].includes(payload.type) ? payload.type : 'fixed'; const source = ['client', 'ai_generated'].includes(payload.source) ? payload.source : 'ai_generated'; const temporary = payload.temporary !== false; const status = ['draft', 'active', 'disabled'].includes(payload.status) ? payload.status : 'draft'; if (status === 'active' && (temporary || source === 'ai_generated')) fail('DRAFT_CANNOT_ACTIVATE', 'AI 或临时优惠券草案不能启用。'); const id = String(payload.id || stableDocumentId('ctpl', [String(payload.name || ''), now.toISOString()])); const old = await store.getById('coupon_templates', id); const row = { _id: id, name: String(payload.name || '').slice(0, 100), type, discountCent: i(payload.discountCent), discountRateBps: i(payload.discountRateBps), maxDiscountCent: i(payload.maxDiscountCent), minSpendCent: i(payload.minSpendCent), scopeType: ['all', 'product', 'category'].includes(payload.scopeType) ? payload.scopeType : 'all', scopeIds: Array.isArray(payload.scopeIds) ? [...new Set(payload.scopeIds.map(String))].slice(0, 100) : [], totalLimit: i(payload.totalLimit), perUserLimit: Math.max(1, i(payload.perUserLimit, 1)), validFrom: String(payload.validFrom || ''), validTo: String(payload.validTo || ''), status, source, temporary, version: i(old && old.version, 0) + 1, createdBy: admin._id, createdAt: old && old.createdAt || now.toISOString(), updatedAt: now.toISOString() }; if (!row.name || (type === 'fixed' ? row.discountCent < 1 : row.discountRateBps < 1 || row.discountRateBps > 10000)) fail('VALIDATION_ERROR', '优惠券配置不合法。'); await store.set('coupon_templates', id, row); return row; }

async function pointsAccount({ store, user }) { const x = await store.getById('points_accounts', stableDocumentId('points', [user._id])); return { account: x || { userId: user._id, balance: 0, lifetimeEarned: 0 } }; }
async function pointsSignIn({ store, user, payload, now }) { const day = now.toISOString().slice(0, 10); const id = stableDocumentId('signin', [user._id, day]); return store.runTransaction(async (tx) => { const old = await tx.getById('points_ledger', id); const aid = stableDocumentId('points', [user._id]); const a = await tx.getById('points_accounts', aid) || { _id: aid, userId: user._id, balance: 0, lifetimeEarned: 0 }; if (old) return { account: a, ledger: old, idempotent: true }; const change = 1; const ledger = { _id: id, userId: user._id, action: 'daily_sign_in', change, balanceAfter: a.balance + change, idempotencyKey: String(payload.idempotencyKey || day), createdAt: now.toISOString() }; await tx.set('points_ledger', id, ledger); await tx.set('points_accounts', aid, { ...a, balance: a.balance + change, lifetimeEarned: a.lifetimeEarned + change, updatedAt: now.toISOString() }); return { account: { ...a, balance: a.balance + change, lifetimeEarned: a.lifetimeEarned + change }, ledger, idempotent: false }; }); }
async function membership({ store, user }) { const account = (await pointsAccount({ store, user })).account; const levels = (await store.list('membership_levels', { where: { status: 'active' }, page: 1, pageSize: 100, allowMissingCollection: true })).rows.filter((x) => x.temporary !== true && x.source !== 'ai_generated').sort((a, b) => i(b.minPoints) - i(a.minPoints)); const level = levels.find((x) => i(account.lifetimeEarned) >= i(x.minPoints)) || null; return { profile: { userId: user._id, points: i(account.balance), lifetimePoints: i(account.lifetimeEarned), levelCode: level && level.code || '' }, level }; }
async function userRows({ store, user, collection, payload }) { return list(store, collection || payload.collection, { userId: user._id }, payload); }
async function reviewCreate({ store, user, payload, now }) { const order = await store.getById('orders', String(payload.orderId || '')); if (!order || order.userId !== user._id || order.status !== 'completed') fail('REVIEW_NOT_AVAILABLE', '订单尚不可评价。'); const orderItemId = String(payload.orderItemId || ''); const item = (order.itemsSnapshot || []).find((x, n) => orderItemId === String(x.orderItemId || (order.itemIds || [])[n] || '')); if (!item) fail('ORDER_ITEM_NOT_FOUND', '订单项不存在。'); const key = String(payload.idempotencyKey || ''); if (!key) fail('IDEMPOTENCY_KEY_REQUIRED', '评价需要幂等键。'); const id = stableDocumentId('review', [user._id, orderItemId]); const old = await store.getById('reviews', id); if (old) { if (old.idempotencyKey !== key || old.orderId !== order._id) fail('REVIEW_ALREADY_EXISTS', '该订单项已评价。'); return { review: old, idempotent: true }; } const rating = i(payload.rating); if (rating < 1 || rating > 5) fail('VALIDATION_ERROR', '评分必须是 1 到 5。'); const mediaIds = Array.isArray(payload.mediaIds) ? [...new Set(payload.mediaIds.map(String))].slice(0, 9) : []; for (const mediaId of mediaIds) { const media = await store.getById('media_assets', mediaId); if (!media || media.userId !== user._id || media.purpose !== 'review_evidence' || media.enabled === false) fail('REVIEW_MEDIA_INVALID', '评价媒体不存在或不属于当前用户。'); } const row = { _id: id, userId: user._id, orderId: order._id, orderItemId, productId: item.productId, skuId: item.skuId, rating, content: String(payload.content || '').slice(0, 1000), mediaIds, status: 'pending', idempotencyKey: key, createdAt: now.toISOString(), updatedAt: now.toISOString() }; await store.set('reviews', id, row); return { review: row, idempotent: false }; }
async function publicReviews({ store, payload }) { return list(store, 'reviews', { productId: String(payload.productId || ''), status: 'approved' }, payload); }
async function invoiceTitleUpsert({ store, user, payload, now }) { const type = payload.type === 'company' ? 'company' : 'personal'; const id = String(payload.id || stableDocumentId('invtitle', [user._id, now.toISOString()])); const old = await store.getById('invoice_titles', id); if (old && old.userId !== user._id) fail('INVOICE_TITLE_NOT_FOUND', '发票抬头不存在。'); const row = { _id: id, userId: user._id, type, name: String(payload.name || '').slice(0, 100), taxNo: type === 'company' ? String(payload.taxNo || '').slice(0, 30) : '', address: String(payload.address || '').slice(0, 200), bankName: String(payload.bankName || '').slice(0, 100), bankAccount: String(payload.bankAccount || '').slice(0, 80), createdAt: old && old.createdAt || now.toISOString(), updatedAt: now.toISOString() }; if (!row.name || type === 'company' && !row.taxNo) fail('VALIDATION_ERROR', '发票抬头信息不完整。'); await store.set('invoice_titles', id, row); return { title: row }; }
async function invoiceRequest({ store, user, payload, now }) { const key = String(payload.idempotencyKey || ''); if (!key) fail('IDEMPOTENCY_KEY_REQUIRED', '发票申请需要幂等键。'); const id = stableDocumentId('invoice', [user._id, key]); const old = await store.getById('invoices', id); if (old) return { invoice: old, idempotent: true }; const order = await store.getById('orders', String(payload.orderId || '')); const title = await store.getById('invoice_titles', String(payload.titleId || '')); if (!order || order.userId !== user._id || !['paid', 'credit_invoiced'].includes(order.paymentStatus) || !title || title.userId !== user._id) fail('INVOICE_NOT_AVAILABLE', '订单或发票抬头不可用。'); const titleSnapshot = { _id: title._id, type: title.type, name: title.name, taxNoMasked: title.taxNoMasked || '', address: title.address || '', bankName: title.bankName || '', bankAccountMasked: title.bankAccountMasked || '' }; const row = { _id: id, userId: user._id, organizationId: order.organizationId || '', orderId: order._id, amountCent: order.totalAmountCent, titleSnapshot, email: String(payload.email || '').slice(0, 120), status: 'provider_unconfigured', providerStatus: 'unconfigured', idempotencyKey: key, createdAt: now.toISOString(), updatedAt: now.toISOString() }; await store.set('invoices', id, row); return { invoice: row, idempotent: false }; }
async function storedAccount({ store, user }) { const a = await store.getById('stored_value_accounts', stableDocumentId('stored', [user._id])); return { account: a || { userId: user._id, balanceCent: 0, status: 'unavailable', realRechargeEnabled: false } }; }
async function topupIntent({ store, user, payload, now }) { const key = String(payload.idempotencyKey || ''); if (!key) fail('IDEMPOTENCY_KEY_REQUIRED', '充值意向需要幂等键。'); const id = stableDocumentId('topup', [user._id, key]); const old = await store.getById('stored_value_topup_intents', id); if (old) return { intent: old, idempotent: true }; const row = { _id: id, userId: user._id, amountCent: i(payload.amountCent), status: 'unavailable', reason: 'payment_not_configured', balanceChanged: false, idempotencyKey: key, createdAt: now.toISOString() }; if (row.amountCent < 1) fail('VALIDATION_ERROR', '充值金额不合法。'); await store.set('stored_value_topup_intents', id, row); return { intent: row, idempotent: false }; }
module.exports = { bundleList, bundleGet, bundleQuote, adminBundleUpsert, couponTemplates, couponClaim, couponList, adminCouponUpsert, pointsAccount, pointsSignIn, membership, userRows, reviewCreate, publicReviews, invoiceTitleUpsert, invoiceRequest, storedAccount, topupIntent, list };
